### ISSUE TITLE
Refactor and rewrite queue for processing events

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/feathers-giveth#435]

**Comment by mohammadranjbarz** [comment]
@aminlatifi  @MoeNick 
I deployed this PR to `UAT`  ( manually deployed without merging PR)

The event processing queue  changed a lot (so the things about blockchain should be tested), and I would appreciate it if you test the application ( I tested creating milestone, donate to milestone, delegate to milestone, and works fine)

PS: Ropsten mining is slow today so your donations may be takes about 10-15 minutes, be patient it's not our bug

**Comment by MoeNick** [comment]
> @aminlatifi @MoeNick
> I deployed this PR to `UAT` ( manually deployed without merging PR)
> 
> The event processing queue changed a lot (so the things about blockchain should be tested), and I would appreciate it if you test the application ( I tested creating milestone, donate to milestone, delegate to milestone, and works fine)
> 
> PS: Ropsten mining is slow today so your donations may be takes about 10-15 minutes to be mined, be patient it's not our bug
I think it's not related.  :)) But:
this donation was accepted and committed, but after changing account, it still show it as pending unless i need to refresh the page and it has been showed-up successfully.
![image](https://user-images.githubusercontent.com/80677512/115661233-5e51d880-a352-11eb-901b-31b7fd74737c.png)
